sudo: false

language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

script: make test

deploy:
  provider: pypi
  user: cmccandless
  password:
    secure: UI905mc7Xi2Hg1eZhSLfRqeR278TBQqC4sKgUuPugsnk4VZjWvbOD8bumG1E5pvVoasP1htRrxNM8qo8/sSa0AVCsOHt8dTPBJaY4ypsoIcKqsZbadfSckHlDpNE5OlpLqQyXQkIwBIXBogzdCmhC96LoTUg7yuJMyv0ZxsK5GpIlgtqyKrofGOwvwEBUnMkGGN99Grk5M9cDjBCAXPhCgVzMves/SK72h2TvthCBmI1b3dKfkYGczNi8O4ZEG3rHpbM9ATSXwFE4CPxlExKG2bmPto/hdwGQAYXml+5Mp2BGYjX6Fa8VKzjn4HkEmKB5iR538WUY/EqRZWf2Do32PQBWgT9nqPaNwMzm0zwRZWckp1MnzQWkgV7MJqBQKBjzbxOX7YNuWA6cwaLzmkrnGCzLy7fmxZ5tEeLi3UcDUaygTEWmfyiT5d47jNL95itqUeZDd1vbzjZIRzipasJk0zv97mFgdtR9lJDLoq0bO8fUpO3BWVz9IiIAEtptpLszcdDkwRp8oaxj6QoENsMS3lGA/GA7Sqs3mBZq1jvNsgk526+LGzGXLLJiClzfql+poYN1zwl8dXoNVCsAozFf11F+E8vEVdqyc2Pm1A7fXbxuFPWLmr8vWdrylqy2vg3v2QTY3+p9X/aXys/Sym4giQs+SIV5EwNNS9hacvSoWY=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: cmccandless/safepass
